{% set name = "PySimpleGUIWeb" %}
{% set version = "0.39.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name }}-{{ version }}.tar.gz
  sha256: bf678836226fc8450c965fb209bfb04809bbf6275139aa5a71808b07a3fa32c5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4
    - remi

test:
  imports:
    - PySimpleGUIWeb

about:
  home: https://github.com/PySimpleGUI/PySimpleGUI
  license: LGPL-3.0
  license_family: LGPL
  license_file: license.txt
  description: GUI SDK Launched in 2018 Actively developed and supported. Super-simple to create custom GUI's.  Python 2.7 & 3 Support. 100 Demo programs & Cookbook for rapid start. Extensive documentation. Examples using Machine Learning(GUI, OpenCV Integration,  Chatterbot), Rainmeter Style Floating Desktop Widgets, Matplotlib
    + Pyplot integration, add GUI to command line scripts, PDF & Image Viewer. Great for beginners as well as advanced GUI programmers
  summary: GUI SDK Launched in 2018 Actively developed and supported.
  doc_url: http://www.pysimplegui.org/
  dev_url: https://github.com/PySimpleGUI/PySimpleGUI

extra:
  recipe-maintainers:
    - silun
